void run_display(void);
void level_announcement(void);
void display_quit_query(void);
void clear_quit_query(void);

enum
{
BMP_WHATEVER,

ENEMY1_BMPS
};

enum
{
RLE_ENEMY1_STINGER,
RLE_ENEMY1_DRIFTER,
RLE_ENEMY1_WANDERER,
RLE_ENEMY1_SUN,
RLE_ENEMY1_SUN_WHITE,
RLE_ENEMY1_JELLY1,
RLE_ENEMY1_JELLY2,
RLE_ENEMY1_JELLY3,
RLE_ENEMY1_JELLY4,
RLE_ENEMY1_JELLY5,
RLE_ENEMY1_JELLY6,
RLE_ENEMY1_MINETHROWER,
RLE_ENEMY1_MINETHROWER2,
RLE_ENEMY1_CURVER,
RLE_ENEMY1_STINGER2,
RLE_ENEMY1_BLASTER,
RLE_ENEMY1_STINGER3,
RLE_ENEMY1_FLAKKER,
RLE_ENEMY1_SUPERJELLY,
RLE_ENEMY1_HIVE,
RLE_ENEMY1_STINGER4,
RLE_ENEMY1_FLAKKER2,
RLE_ENEMY1_BOLTER,
RLE_ENEMY1_BOLTER2,
RLE_ENEMY1_TORPER1_1,
RLE_ENEMY1_TORPER1_2,
RLE_ENEMY1_TORPER1_3,
RLE_ENEMY1_TORPER1_4,
RLE_ENEMY1_HURLER,
RLE_ENEMY1_HURLER2,
ENEMY1_RLES
};

enum
{
RLE_ENEMY2_CRAWLER2_D,
RLE_ENEMY2_CRAWLER2_L,
RLE_ENEMY2_CRAWLER2_R,
RLE_ENEMY2_CRAWLER3_D,
RLE_ENEMY2_CRAWLER3_L,
RLE_ENEMY2_CRAWLER3_R,
RLE_ENEMY2_CRAWLER4_D,
RLE_ENEMY2_CRAWLER4_L,
RLE_ENEMY2_CRAWLER4_R,
ENEMY2_RLES
};

enum
{
RLE_ENEMY3_FIREBASE,
RLE_ENEMY3_FIREBASE2,
RLE_ENEMY3_FIREBASE3,
RLE_ENEMY3_BOSS1,
RLE_ENEMY3_BOSS3,
RLE_ENEMY3_BOSS4,
ENEMY3_RLES
};

enum
{
RLE_SMALL1_GREEN_BLOB_L,
RLE_SMALL1_GREEN_BLOB_M,
RLE_SMALL1_GREEN_BLOB_S,
RLE_SMALL1_BLUE_BLOB_L,
RLE_SMALL1_BLUE_BLOB_M,
RLE_SMALL1_BLUE_BLOB_S,
RLE_SMALL1_ORANGE_BLOB_L,
RLE_SMALL1_ORANGE_BLOB_M,
RLE_SMALL1_ORANGE_BLOB_S,
RLE_SMALL1_YELLOW_BLOB_L,
RLE_SMALL1_YELLOW_BLOB_M,
RLE_SMALL1_YELLOW_BLOB_S,
RLE_SMALL1_PREMINE,
RLE_SMALL1_MINE1,
RLE_SMALL1_MINE2,
RLE_SMALL1_MINE3,
RLE_SMALL1_PRESEEKMINE,
RLE_SMALL1_SEEKMINE1,
RLE_SMALL1_SEEKMINE2,
RLE_SMALL1_SEEKMINE3,
RLE_SMALL1_PURPLE_BLOB_L,
RLE_SMALL1_PURPLE_BLOB_M,
RLE_SMALL1_PURPLE_BLOB_S,
RLE_SMALL1_RED_BLOB_L,
RLE_SMALL1_RED_BLOB_M,
RLE_SMALL1_RED_BLOB_S,

SMALL1_RLES
};


enum
{
BMP_SMALL2_MISSILE_1,
BMP_SMALL2_MISSILE_2,
BMP_SMALL2_MISSILE_3,
BMP_SMALL2_MISSILE_4,
BMP_SMALL2_MISSILE_5,
BMP_SMALL2_MISSILE_6,
BMP_SMALL2_MISSILE_7,
BMP_SMALL2_BOMB,
BMP_SMALL2_SIDE_BOMB,

SMALL2_BMPS
};

enum
{
RLE_LSHIP_BLUE,
RLE_LSHIP_GREEN,
RLE_LSHIP_YELLOW,
RLE_LSHIP_RED,
RLE_LSHIP_LINES
};


enum
{
STYLE_NONE,
STYLE_HURRY,
STYLE_ONLINE,
STYLE_UPGRADE1,
STYLE_UPGRADE2,
STYLE_UPGRADE3,
STYLE_UPGRADE4,
STYLE_UPGRADE5,
STYLE_NEWLEVEL
};

void init_messages(void);
void send_message(int play, const char *msg, int style);

