void init_palette(void);
//int adjust_lit_colour(int col, int lit);

enum
{
TRANS_WHITE = 195,
TRANS_PURPLE, // 196
TRANS_LBLUE, // 197
TRANS_DBLUE, // 198
TRANS_YELLOW, // 199
TRANS_LGREEN, // 200
TRANS_DGREEN, // 201
TRANS_LORANGE, // 202
TRANS_DORANGE, // 203
TRANS_LRED, // 204
TRANS_DRED, // 205
TRANS_WHITE2, // 206
// Special white which doesn't overwrite other colours (for shockwaves etc)
TRANS_LGREY, // 207
TRANS_DGREY, // 208

TRANS_GREY, // 209
// GREY is special. It's the only transparency which preserves colour, not
//  just brightness, and it takes up four times as much space in the
//  palette as the others. WHITE, LGREY and DGREY are just normal
//  transparencies, and both will overwrite GREY.
// GREY should be last, but for:
TRANS_END //207
// must be the last trans + 1
};

/*extern int trans_colours_array [7];
extern int actor_colours_array [7];*/

int colour_to_trans(int y);


enum
{
COLOUR_BLACK = 192,
COLOUR_GREY1,
COLOUR_GREY2,
COLOUR_GREY3,
COLOUR_GREY4,
COLOUR_GREY5,
COLOUR_GREY6,
//COLOUR_GREY7,
COLOUR_WHITE,
COLOUR_ORANGE1,
COLOUR_ORANGE2,
COLOUR_ORANGE3,
COLOUR_ORANGE4,
COLOUR_ORANGE5,
COLOUR_ORANGE6,
COLOUR_ORANGE7,
COLOUR_ORANGE8,
COLOUR_YELLOW1,
COLOUR_YELLOW2,
COLOUR_YELLOW3,
COLOUR_YELLOW4,
COLOUR_YELLOW5,
COLOUR_YELLOW6,
COLOUR_YELLOW7,
COLOUR_YELLOW8,
COLOUR_RED1,
COLOUR_RED2,
COLOUR_RED3,
COLOUR_RED4,
COLOUR_RED5,
COLOUR_RED6,
COLOUR_RED7,
COLOUR_RED8,
COLOUR_GREEN1,
COLOUR_GREEN2,
COLOUR_GREEN3,
COLOUR_GREEN4,
COLOUR_GREEN5,
COLOUR_GREEN6,
COLOUR_GREEN7,
COLOUR_GREEN8,
COLOUR_BLUE1,
COLOUR_BLUE2,
COLOUR_BLUE3,
COLOUR_BLUE4,
COLOUR_BLUE5,
COLOUR_BLUE6,
COLOUR_BLUE7,
COLOUR_BLUE8,
COLOUR_PURPLE1,
COLOUR_PURPLE2,
COLOUR_PURPLE3,
COLOUR_PURPLE4,
COLOUR_PURPLE5,
COLOUR_PURPLE6,
COLOUR_PURPLE7,
COLOUR_PURPLE8,
COLOUR_X1,
COLOUR_X2,
COLOUR_X3,
COLOUR_X4,
COLOUR_X5,
COLOUR_X6,
COLOUR_X7,
COLOUR_X8
//COLOUR_WRITING,
//COLOUR_BROWN

};

